# Generated by Django 3.2.12 on 2025-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
