# Generated by Django 3.2.12 on 2025-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.CharField(choices=[('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Bad', 'Bad')], max_length=15)),
            ],
        ),
    ]
